name: myFirstWorkflow
on:
  push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
    - name: clone repo
      uses: actions/checkout@v4
    - name: list repo files
      run: ls -lart
    - name: Print Hello World
      run: echo "Hello World"